# Generated by Django 3.0.5 on 2020-04-15 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
