# Generated by Django 3.0.5 on 2020-04-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='subject',
        ),
    ]
